import { MenuItem } from "@/types/types";
import {
  LayoutDashboard,
  BarChart3,
  Building2,
  Users,
  Truck,
  Plus,
  Eye,
  FileText,
  Receipt,
  PlusCircle,
  Mail,
  Shield,
  DollarSign,
  File,
  Bell,
  CreditCard,
  Printer,
  Edit,
  Download,
  Search,
  Book,
  Wallet,
  Settings,
  UserCheck,
  Shuffle,
  MapPin,
  Lock,
  User,
} from "lucide-react";

export const routeConfig: MenuItem[] = [
{
  title: "Dashboard",
  path: "/dashboard",
  icon: LayoutDashboard,
  subject: "dashboard",
},
{
  title: "user",
  path: "/user",
  icon: LayoutDashboard,
  subject: "user",
},
{
  title: "Profile",
  path: "/profile",
  icon: User,
  subject: "profile",
},
{
  title: "Super Staff Users",
  path: "/super-staff-users",
  icon: Users,
  subject: "super-staff-users",
},
{
  title: "Staff Users",
  path: "/staff",
  icon: Users,
  subject: "staff-users",
},
{
  title: "Distributor Users",
  path: "/distributor-users",
  icon: Users,
  subject: "distributor-users",
},
{
  title: "Retailer Users",
  path: "/retailer-users",
  icon: Users,
  subject: "retailer-users",
},
{
  title: "ITR Application",
  path: "/itr-application",
  icon: FileText,
  subject: "itr-application",
},
{
  title: "PAN Application",
  path: "/pan-application",
  icon: FileText,
  subject: "pan-application",
},
{
  title: "GST Application",
  path: "/gst-application",
  icon: FileText,
  subject: "gst-application",
},
{
  title: "Credit Card Application",
  path: "/credit-card-application",
  icon: CreditCard,
  subject: "credit-card-application",
},
{
  title: "Print PVC",
  path: "/print-pvc",
  icon: Printer,
  subject: "print-pvc",
},
{
  title: "Aadhar Change",
  path: "/aadhar-change",
  icon: Edit,
  subject: "aadhar-change",
},
{
  title: "Download Voter Card",
  path: "/download-voter-card",
  icon: Download,
  subject: "download-voter-card",
},
{
  title: "Find Pan Card",
  path: "/find-pan-card",
  icon: Search,
  subject: "find-pan-card",
},
{
  title: "Find Aadhar Card",
  path: "/find-aadhar-card",
  icon: Search,
  subject: "find-aadhar-card",
},
{
  title: "Ledger Users",
  path: "/ledger-users",
  icon: Book,
  subject: "ledger-users",
},
{
  title: "Fund Request",
  path: "/fund-request",
  icon: Wallet,
  subject: "fund-request",
},
{
  title: "General Setting",
  path: "/general-setting",
  icon: Settings,
  subject: "general-setting",
},
{
  title: "Assign Retailer",
  path: "/assign-retailer",
  icon: UserCheck,
  subject: "assign-retailer",
},
{
  title: "Change Role",
  path: "/change-role",
  icon: Shuffle,
  subject: "change-role",
},
{
  title: "Pincode",
  path: "/pincode",
  icon: MapPin,
  subject: "pincode",
},
{
  title: "Change Password",
  path: "/change-password",
  icon: Lock,
  subject: "change-password",
},

];
